name: Code analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run SpotBugs and Checkstyle
        run: ./gradlew spotbugsMain checkstyleMain

      - name: Upload analysis results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-results
          path: |
            build/reports/spotbugs/
            build/reports/checkstyle/